#Teste de tipos primitivos
algo = input('Digite Algo: ')
print('O tipo primitivo é?', type(algo))
print('Só tem espaços?', algo.isspace())
print('É numérico?', algo.isnumeric())
print('É alfabético?', algo.isalpha())
print('É alfanumérico?', algo.isalnum())
print('Está em MAIÚSCULAS?', algo.isupper())
print('Está em minúsculas?', algo.islower())
print('Está capitalizada?', algo.istitle())
